"""The construction specs of every icon (`visual_assets/icons/icon_specs.yaml`), their validation and the generated style-guide table (`TCK-20261008-VISUAL-ASSETS-ICON-RECOGNISABILITY-CHECKS`).

A spec says what an icon must be (orientation, proportions in pixels, parts, one line "reads as", one line "must not read as") BEFORE it is drawn, and carries the words the blind recognition check
scores with (`synonyms`) and the wrong answers it offers (`distractors`). Pure Python, read-only.

    python -m tests.visual_assets.icon_specs --table     # the markdown table that docs/assets/icon_style_guide.md must contain
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

from tests.visual_assets.pilot_colour_vision import REPO

SPECS_FILE = REPO / "visual_assets" / "icons" / "icon_specs.yaml"
KEYS_FILE = REPO / "visual_assets" / "catalog" / "definitions" / "visual_keys.yaml"
REQUIRED = ("status", "subject", "theme", "modern_lookalikes_to_avoid", "orientation", "proportions", "parts", "reads_as", "must_not_read_as", "synonyms", "distractors")
THEME_PREFIXES = ("medieval", "ancient", "abstract ui glyph")  # D21: an object of the medieval fantasy world, or an abstract UI glyph that names no object
# Words that name modern objects. They may appear in `modern_lookalikes_to_avoid`, `must_not_read_as` and `distractors` (that is what those fields are for) but never in the fields that DESCRIBE the icon.
MODERN_TERMS = ("suitcase", "briefcase", "toolbox", "wrench", "spanner", "zip", "zipper", "plastic", "lightbulb", "light bulb", "smartphone", "laptop", "paperback", "bulletproof", "sneaker", "hoodie", "road sign", "warning sign", "warning triangle", "traffic cone", "gear", "cog", "cogwheel")
STATUSES = ("v2", "adopted", "revision")  # revision: a target for a new revision (r0002) of an adopted icon
TABLE_BEGIN = "<!-- icon-specs-table:begin (generated by python -m tests.visual_assets.icon_specs --table; do not edit by hand) -->"
TABLE_END = "<!-- icon-specs-table:end -->"


@dataclass(frozen=True)
class Spec:
    key: str
    family: str
    size: int
    status: str
    subject: str
    theme: str
    modern_lookalikes: tuple[str, ...]
    orientation: str
    proportions: str
    parts: tuple[str, ...]
    reads_as: str
    must_not_read_as: str
    synonyms: tuple[str, ...]
    distractors: tuple[str, ...]


def has_word(text: str, term: str) -> bool:
    """Whole-word match (an optional plural s or es): `bow` is not in `crossbow`, nor `pick` in `picket`. Used by the scoring and by the distractor check, so they can never disagree."""
    return re.search(rf"(?<![a-z]){re.escape(term.lower())}(?:e?s)?(?![a-z])", text.lower()) is not None


def family_of(key: str) -> str:
    return key.split(".")[1]


def load(path: Path = SPECS_FILE) -> dict[str, Spec]:
    data = yaml.safe_load(path.read_text())
    families = data["families"]
    out = {}
    for key, raw in data["icons"].items():
        missing = [f for f in REQUIRED if f not in raw]
        if missing:
            raise ValueError(f"{key}: spec lacks {missing}")
        if raw["status"] not in STATUSES:
            raise ValueError(f"{key}: status {raw['status']!r} is not one of {STATUSES}")
        family = family_of(key)
        if family not in families:
            raise ValueError(f"{key}: family {family!r} has no convention entry")
        out[key] = Spec(
            key, family, int(families[family]["size"]), raw["status"], raw["subject"], raw["theme"], tuple(raw["modern_lookalikes_to_avoid"]), raw["orientation"], raw["proportions"], tuple(raw["parts"]), raw["reads_as"],
            raw["must_not_read_as"], tuple(s.lower() for s in raw["synonyms"]), tuple(raw["distractors"]),
        )
    return out


def registered_icon_keys(path: Path = KEYS_FILE) -> list[str]:
    keys = yaml.safe_load(path.read_text())["keys"]
    return sorted(k["key"] for k in keys if k["key"].startswith("icon."))


def conventions(path: Path = SPECS_FILE) -> dict[str, dict]:
    return yaml.safe_load(path.read_text())["families"]


def problems(specs: dict[str, Spec], registered: list[str]) -> list[str]:
    """Everything wrong with a spec set; empty when it is complete and self-consistent."""
    out = []
    if sorted(specs) != sorted(registered):
        out.append(f"spec keys differ from the registered icon keys: only in specs {sorted(set(specs) - set(registered))}, only in registry {sorted(set(registered) - set(specs))}")
    for key, s in specs.items():
        if len(s.synonyms) < 2 or len(s.distractors) < 4:
            out.append(f"{key}: needs at least 2 synonyms and 4 distractors")
        clash = [d for d in s.distractors if any(has_word(d, w) for w in s.synonyms)]
        if clash:
            out.append(f"{key}: distractor(s) {clash} would count as a correct answer (they contain a synonym)")
        if not s.parts:
            out.append(f"{key}: no parts listed")
        if not s.theme.lower().startswith(THEME_PREFIXES):
            out.append(f"{key}: the theme must start with one of {THEME_PREFIXES} (D21), got {s.theme!r}")
        if not s.modern_lookalikes:
            out.append(f"{key}: no modern lookalikes to avoid are listed")
        described = " ".join([s.subject, s.theme, s.orientation, s.proportions, " ".join(s.parts), s.reads_as])
        modern = [t for t in MODERN_TERMS if has_word(described, t)]
        if modern:
            out.append(f"{key}: the description names a modern object {modern} (D21: nothing modern; such words belong in modern_lookalikes_to_avoid or must_not_read_as)")
    return out


def table(specs: dict[str, Spec]) -> str:
    lines = [TABLE_BEGIN, "", "| Key | Size | Status | Subject | Theme | Modern lookalikes to avoid | Orientation | Proportions (px) | Parts | Reads as | Must not read as |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for key in sorted(specs):
        s = specs[key]
        lines.append(f"| `{key}` | {s.size} | {s.status} | {s.subject} | {s.theme} | {'; '.join(s.modern_lookalikes)} | {s.orientation} | {s.proportions} | {', '.join(s.parts)} | {s.reads_as} | {s.must_not_read_as} |")
    lines += ["", TABLE_END]
    return "\n".join(lines)


if __name__ == "__main__":
    if "--table" in sys.argv:
        print(table(load()))
    else:
        issues = problems(load(), registered_icon_keys())
        print("\n".join(issues) or "specs complete and consistent")
        sys.exit(1 if issues else 0)
