"""Opt-in installer for the repository's git hooks (prek pre-commit + the post-commit reindex hook).

    python3 tools/hooks/install_git_hooks.py install [--repo DIR]
    python3 tools/hooks/install_git_hooks.py uninstall [--repo DIR]

Behind `make install-prek-hooks` / `make uninstall-prek-hooks`. Nothing else may call it: hooks are never
installed from another target, a script, a CI step or a session hook (TCK-20261003-PREK-GIT-HOOKS-OPT-IN).

The hooks directory is the one `git` resolves for the repository, which is the **common** directory shared by
every worktree on the machine, so installing here affects all of them. Install is idempotent and never
overwrites:

- `post-commit`: installed only when absent; byte-identical -> no change; any other existing hook is kept and
  reported (the older `make install-hooks` target copies over it, this one does not).
- `pre-commit`: `prek install --hook-type pre-commit`. If a foreign pre-commit hook exists prek keeps it as
  `pre-commit.legacy` and runs it too. An already prek-generated hook is left untouched.

Uninstall removes only what this script installed: prek's pre-commit shim (`prek uninstall` restores a legacy
hook) and a post-commit hook that is byte-identical to `tools/hooks/post-commit-reindex.sh`. Every other hook
(for example `post-merge`) is never touched.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Sequence

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
POST_COMMIT_SOURCE = Path("tools/hooks/post-commit-reindex.sh")
PREK_MARKER = "File generated by prek"
WARNING = (
    "[hooks] note: the git hooks directory is shared by every worktree on this machine; installing here "
    "affects all of them (the hooks skip, never fail, where the environment is missing)."
)


class InstallError(Exception):
    """A hook could not be installed or removed; nothing was overwritten."""


def hooks_dir(repo: Path) -> Path:
    """The hooks directory git uses for `repo` (shared by all its worktrees)."""
    done = subprocess.run(
        ["git", "rev-parse", "--path-format=absolute", "--git-path", "hooks"],
        cwd=repo, capture_output=True, text=True, check=False,
    )
    if done.returncode != 0:
        raise InstallError(f"not a git repository: {repo}")
    return Path(done.stdout.strip())


def find_prek() -> str:
    """The prek binary beside the running interpreter (the project environment), else on PATH."""
    beside = Path(sys.executable).parent / "prek"
    found = str(beside) if beside.exists() else shutil.which("prek")
    if found is None:
        raise InstallError("prek not found: install the project environment (uv sync)")
    return found


def _is_prek_hook(path: Path) -> bool:
    return path.is_file() and PREK_MARKER in path.read_text(encoding="utf-8", errors="replace")


def _prek(repo: Path, *args: str) -> None:
    done = subprocess.run([find_prek(), *args], cwd=repo, capture_output=True, text=True, check=False)
    if done.returncode != 0:
        raise InstallError(f"prek {' '.join(args)} failed: {' '.join((done.stderr or done.stdout).split())[:300]}")
    for line in (done.stdout + done.stderr).splitlines():
        if line.strip():
            print(f"[hooks]   prek: {line.strip()}")


def install(repo: Path) -> list[str]:
    """Install both hooks; returns what happened, one line per hook. Never overwrites an existing hook."""
    hooks = hooks_dir(repo)
    hooks.mkdir(parents=True, exist_ok=True)
    source = repo / POST_COMMIT_SOURCE
    target = hooks / "post-commit"
    report = []
    if not target.exists():
        shutil.copyfile(source, target)
        target.chmod(0o755)
        report.append("post-commit: installed (incremental knowledge reindex)")
    elif target.read_bytes() == source.read_bytes():
        report.append("post-commit: already installed, unchanged")
    else:
        report.append("post-commit: a different hook already exists and was kept (not overwritten)")
    pre_commit = hooks / "pre-commit"
    if _is_prek_hook(pre_commit):
        report.append("pre-commit: prek hook already installed, unchanged")
    else:
        foreign = pre_commit.exists()
        _prek(repo, "install", "--hook-type", "pre-commit")
        report.append("pre-commit: prek hook installed" + (" (the existing hook is kept as pre-commit.legacy and still runs)" if foreign else ""))
    return report


def uninstall(repo: Path) -> list[str]:
    """Remove only what `install` put there; returns what happened, one line per hook."""
    hooks = hooks_dir(repo)
    report = []
    pre_commit = hooks / "pre-commit"
    if _is_prek_hook(pre_commit):
        _prek(repo, "uninstall", "--hook-type", "pre-commit")
        report.append("pre-commit: prek hook removed (a legacy hook, if any, is restored)")
    else:
        report.append("pre-commit: no prek hook installed, nothing to remove")
    target = hooks / "post-commit"
    source = repo / POST_COMMIT_SOURCE
    if target.exists() and target.read_bytes() == source.read_bytes():
        target.unlink()
        report.append("post-commit: removed (it was identical to tools/hooks/post-commit-reindex.sh)")
    else:
        report.append("post-commit: not ours or not installed, left alone")
    return report


def main(argv: Sequence[str] | None = None) -> int:
    """Command-line entry point."""
    parser = argparse.ArgumentParser(prog="python3 tools/hooks/install_git_hooks.py", description=__doc__)
    parser.add_argument("action", choices=("install", "uninstall"))
    parser.add_argument("--repo", type=Path, default=REPO_ROOT, help="repository whose hooks to change (tests use a scratch repo)")
    args = parser.parse_args(argv)
    try:
        print(WARNING)
        for line in (install if args.action == "install" else uninstall)(args.repo):
            print(f"[hooks] {line}")
    except InstallError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
