from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, TYPE_CHECKING
from src_v2.core.enums import ActionType
from src_v2.core.reason import ActionReason, ReasonCode

if TYPE_CHECKING:
    from src_v2.core.updates import EntityUpdate

@dataclass(frozen=True, slots=True)
class ActionProposal:
    """
    An authoritative intent produced by a worker.
    Represents 'Actor + Verb + Target + Reason'.
    """
    actor_id: int
    verb: ActionType
    target_id: Optional[int] = None
    target_pos: Optional[tuple[float, float]] = None
    reason: ActionReason = field(default_factory=lambda: ActionReason(code=ReasonCode.UNKNOWN))
    updates: List[EntityUpdate] = field(default_factory=list) # Side effects generated by this intent
    metadata: Dict[str, Any] = field(default_factory=dict) # Opaque payload for specific action types

    def __repr__(self) -> str:
        return f"Proposal(actor={self.actor_id}, verb={self.verb.name}, reason={self.reason.code.name}, updates={len(self.updates)})"
