from __future__ import annotations
from typing import TYPE_CHECKING

from src.core.models.enums import GoalType
from src.core.models.strategy import ObjectiveKind

if TYPE_CHECKING:
    from src.ai.states.base import AIContext

class ObjectiveToGoalMapper:
    """Translates strategic objectives into tactical utility biases.
    
    This implements phase_2_stage_6. It ensures the tactical GoalEvaluator
    is 'bossed' by the strategic layer's current commitments.
    """

    def get_tactical_biases(self, ctx: AIContext, objective_override: ObjectiveRecord | None = None) -> dict[GoalType, float]:
        """Calculates utility multipliers for goal types based on strategic intent."""
        biases = {gt: 1.0 for gt in GoalType}

        obj = objective_override or ctx.current_objective
        if not obj:
            # No objective? No strategic bias.
            return biases

        # 1. Calculate Confidence Scaling [phase_3_task_9]
        # Most objectives generated by the AI come from leads (rumors, guild intel).
        # We dampen the tactical 'drive' if the lead is uncertain.
        confidence = 1.0
        if obj.leads:
            # Take strongest lead as the driver
            confidence = max(l.certainty for l in obj.leads)
        
        # Scale: [0.5, 1.0]. Even a 0 certainty lead (which shouldn't exist) 
        # gives a 50% dampening rather than 0.
        scale = 0.5 + (0.5 * confidence)

        # 2. Apply biases based on ObjectiveKind
        if obj.kind == ObjectiveKind.VISIT:
            # We want to get to a location. Boost related goals.
            biases[GoalType.REST] = 0.5
            biases[GoalType.EXPLORE] = 1.0 + (1.5 * scale)
            
        elif obj.kind == ObjectiveKind.KILL:
            # Combat focus
            biases[GoalType.COMBAT] = 1.0 + (1.0 * scale)
            biases[GoalType.HUNT] = 1.0 + (1.0 * scale)
            biases[GoalType.FLEE] = 1.0 - (0.2 * scale)
            
        elif obj.kind == ObjectiveKind.COLLECT or obj.kind == ObjectiveKind.INVESTIGATE:
            # Retrieval or analysis
            biases[GoalType.LOOT] = 1.0 + (0.8 * scale)
            biases[GoalType.INVESTIGATE] = 1.0 + (1.0 * scale)
            biases[GoalType.EXPLORE] = 1.0 + (0.5 * scale)
            
        elif obj.kind == ObjectiveKind.SCOUT:
            # Regional scouting
            biases[GoalType.EXPLORE] = 1.0 + (1.5 * scale)
            
        elif obj.kind == ObjectiveKind.TRAIN:
            # Self-improvement focus
            biases[GoalType.COMBAT] = 1.0 + (0.4 * scale)
            biases[GoalType.SOCIAL] = 1.0 + (1.0 * scale) # Visit mentors
            
        elif obj.kind == ObjectiveKind.INTERACT:
            # Social or town focus
            biases[GoalType.SOCIAL] = 1.0 + (1.0 * scale)
            biases[GoalType.REST] = 1.0 + (0.2 * scale)
            
            # Survival needs are special: almost always treated as 1.0 confidence
            if "needs" in obj.objective_id or "survival" in obj.project_id:
                biases[GoalType.EAT] = 5.0
                biases[GoalType.SLEEP] = 5.0
                biases[GoalType.REST] = 5.0
            
        return biases
