"""
src/domains/adventure/schema.py
───────────────────────────────────────────────────────────────────────────────
Phase 3 — Adventure Route Option and Decision schemas.
All dataclasses are frozen so they are immutable.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Optional, Tuple

from src.core.strategic import ProjectState, ObjectiveState


class RouteFamily(str, Enum):
    """Initial Phase 3 route families defining high-level strategic routes."""
    RECOVER = "recover"
    BUY_UPGRADE = "buy_upgrade"
    CRAFT_UPGRADE = "craft_upgrade"
    TRAIN_SKILL = "train_skill"
    TAKE_EASY_QUEST = "take_easy_quest"
    HUNT_WEAK_ENEMY = "hunt_weak_enemy"
    GATHER_RESOURCE = "gather_resource"
    SELL_LOOT_FOR_GOLD = "sell_loot_for_gold"
    ASK_INFORMATION = "ask_information"
    SCOUT_LOCATION = "scout_location"
    FORM_PARTY = "form_party"
    RETURN_TOWN = "return_town"
    DEFER_WITH_REASON = "defer_with_reason"
    QUEST_OPPORTUNITY = "quest_opportunity"
    PROTECT_TARGET = "protect_target"   # E41D: escort urgency route
    OWN_SURVIVAL = "own_survival"       # E41D: self-preservation (deprioritised when escorting)


@dataclass(frozen=True, slots=True)
class AdventureRouteOption:
    """
    Subjective route option generated by AdventureRouteGenerator.
    
    Fields:
        family:                 Name of the route family (e.g. "recover", "craft_upgrade")
        score:                  Calculated suitability score (0.0 to 1.0+)
        confidence:             Subjective confidence in the route's success (0.0 to 1.0)
        expected_benefit:       Subjective reward expectations (0.0 to 1.0)
        expected_risk:          Subjective danger/risk expectations (0.0 to 1.0)
        requirements:           Requirements check details
        blockers:               Active blocker reasons/strings if route is blocked
        source_opportunity_ids: Dynamic world options backing this route
        reason:                 Short descriptive reason for the option
        target_node_id:         Integer node/building ref id resolved from the backing
                                 opportunity's target_id, when available; None otherwise.
    """
    family: RouteFamily
    score: float
    confidence: float
    expected_benefit: float
    expected_risk: float
    requirements: Tuple[Any, ...] = ()
    blockers: Tuple[str, ...] = ()
    source_opportunity_ids: Tuple[str, ...] = ()
    reason: Optional[str] = None
    target_node_id: Optional[int] = None
    quest_id: Optional[str] = None
    # Intermediate scoring terms populated by AdventureRouteScorer (zero before scoring)
    urgency: float = 0.0
    benefit_score: float = 0.0
    personality_bias: float = 0.0
    confidence_bonus: float = 0.0
    risk_penalty: float = 0.0
    blocker_penalty: float = 0.0
    plan_advance_bonus: float = 0.0


@dataclass(frozen=True, slots=True)
class RejectedRoute:
    """Tracks a route option that was evaluated but not selected."""
    family: RouteFamily
    reason: str
    score: float


@dataclass(frozen=True, slots=True)
class AdventureDecisionResult:
    """
    The final output of AdventureDecisionService.
    
    Fields:
        selected:           The chosen AdventureRouteOption, or None if deferred.
        rejected:           Tuple of rejected route options with reasons.
        proposed_project:   The strategic project state representing this decision.
        proposed_objective: The first objective to complete in the project.
        trace:              Explainable evaluation metrics for debugging/logging.
    """
    selected: Optional[AdventureRouteOption]
    rejected: Tuple[RejectedRoute, ...]
    proposed_project: Optional[ProjectState]
    proposed_objective: Optional[ObjectiveState]
    trace: Dict[str, Any] = field(default_factory=dict)
