from __future__ import annotations

import re
from pathlib import Path
from tools.agent_orchestration.loader import load_contract
from tools.agent_orchestration.errors import ContractValidationError
from .errors import (
    CodexAdapterMissingCompanionAssetError,
    CodexAdapterMissingSkillSourceError,
    CodexAdapterWriteGuardError,
)

_AUTHORITATIVE_PIPELINE_NOTE = "All durable-state changes in this simulation are refined through the 32-phase authoritative mutation pipeline defined in `docs/engine/authoritative_pipeline.md` (the Singular Bottleneck Law: no system, worker, or external process may mutate `AuthoritativeState` directly; all changes are represented as a `StateUpdate` and refined through these 32 phases)."
_ID = re.compile(r"[a-z0-9][a-z0-9-]*\Z")

def _assert_write_allowed(repo_root: Path, path: Path, allow: bool) -> None:
    root = repo_root.resolve(); target = path.resolve()
    if target.is_relative_to(root / '.claude') or target.is_relative_to(root / '.codex'):
        raise CodexAdapterWriteGuardError(f"refusing target {target}")
    if not allow and target != root / 'AGENTS.md' and not target.is_relative_to(root / '.agents' / 'skills'):
        raise CodexAdapterWriteGuardError(f"refusing target {target}")

def _body(text: str) -> str:
    """Return the instructional body from either supported Claude skill shape."""
    if not text.startswith("---\n"):
        return text
    parts = text.split("---", 2)
    if len(parts) != 3:
        raise CodexAdapterMissingSkillSourceError("invalid SKILL.md frontmatter")
    return parts[2]

def build_codex_skill_md(repo_root: Path, skill_id: str, description: str) -> str:
    source = repo_root / '.claude' / 'skills' / skill_id / 'SKILL.md'
    if not source.is_file(): raise CodexAdapterMissingSkillSourceError(skill_id)
    body = _body(source.read_text(encoding="utf-8"))
    if not body.startswith("\n"):
        body = "\n" + body
    return f"---\nname: {skill_id}\ndescription: {description!r}\n---" + body

def build_agents_md(repo_root: Path) -> str:
    b=load_contract(repo_root)
    lines=['# AGENTS.md','', 'Generated by `tools/agent_orchestration_codex_adapter/generator.py` from the validated `agent-orchestration/` contract. Do not hand-edit — regenerate instead.','', '## Engine Authority','',_AUTHORITATIVE_PIPELINE_NOTE,'',f"## Workflow: {b.workflow['workflow_id']}",'']
    lines += [f"- {p['name']}" for p in b.workflow['phases']] + ['', '## Roles','']
    policy = b.continuation_policy
    if policy:
        lines += ['', '## Workflow Continuation', '', policy.instruction.strip(), '', 'Do not stop merely for:', '']
        lines += [f"- {item}" for item in policy.non_gates]
        lines += ['']
    lines += [f"- `{r.role_id}` — {r.description}" for r in b.roles] + ['', '## Skills','']
    lines += [f"- `{s['id']}` — {s['description']} (see `.agents/skills/{s['id']}/SKILL.md`)" for s in b.skills['skills']]
    return '\n'.join(lines)+'\n'

def render_codex_guidance(repo_root: Path, target_repo_root: Path, *, allow_outside_contract: bool=False) -> list[Path]:
    try:
        b = load_contract(repo_root)
    except FileNotFoundError as error:
        raise ContractValidationError(f"missing contract file: {error.filename}") from error
    target = target_repo_root
    paths=[target/'AGENTS.md']
    companion_pairs: list[tuple[Path, Path]] = []
    for s in b.skills['skills']:
        if not _ID.fullmatch(s['id']): raise CodexAdapterWriteGuardError(f"invalid skill id: {s['id']}")
        paths.append(target/'.agents'/'skills'/s['id']/'SKILL.md')
        for rel in s.get('companion_assets', []):
            source = repo_root/'.claude'/'skills'/s['id']/rel
            dest = target/'.agents'/'skills'/s['id']/rel
            companion_pairs.append((source, dest))
            paths.append(dest)
    for path in paths: _assert_write_allowed(repo_root, path, allow_outside_contract)
    for source, dest in companion_pairs:
        if not source.is_file():
            raise CodexAdapterMissingCompanionAssetError(f"{dest.parent.name}: declared companion asset not found: {source}")
    paths[0].parent.mkdir(parents=True, exist_ok=True); paths[0].write_text(build_agents_md(repo_root), encoding='utf-8')
    for s in b.skills['skills']:
        path = target/'.agents'/'skills'/s['id']/'SKILL.md'
        path.parent.mkdir(parents=True, exist_ok=True); path.write_text(build_codex_skill_md(repo_root,s['id'],s['description']),encoding='utf-8')
    for source, dest in companion_pairs:
        dest.parent.mkdir(parents=True, exist_ok=True); dest.write_bytes(source.read_bytes())
    return paths
