"""Integration test for Strategic Lead Feedback Loops. [Batch 6]
Verifies that lead outcomes (success/failure) correctly update source trust
and influence future strategic decisions.
"""
import pytest
from src_legacy.core.models.world_state import WorldState
from src_legacy.core.entities.entity import Entity
from src_legacy.core.models.strategy import StrategicStatus, LeadRecord, LeadKind, StrategicState
from src_legacy.ai.brain import AIBrain
from src_legacy.core.models.snapshot import Snapshot
from src_legacy.platform.rng import DeterministicRNG
from src_legacy.config import SimulationConfig
from src_legacy.core.world.grid import Grid
from src_legacy.platform.spatial_hash import SpatialHash
from src_legacy.actions.base import StrategicUpdate
from src_legacy.ai.strategy.strategic_learning_service import StrategicLearningService
from src_legacy.ai.cognition_capacity import CognitionCapacityProfile

@pytest.fixture
def mock_world():
    grid = Grid(100, 100)
    spatial = SpatialHash(cell_size=10)
    world = WorldState(seed=42, grid=grid, spatial_index=spatial)
    world.entities = {}
    return world

@pytest.fixture
def brain():
    config = SimulationConfig()
    return AIBrain(config, DeterministicRNG(0))

def test_source_trust_recalibration(mock_world, brain):
    """Verify that a 'False' lead outcome reduces source trust."""
    hero = Entity(id=1, kind="hero")
    mock_world.add_entity(hero)
    
    # 1. Setup a lead from Source A
    source_a = "informant_a"
    lead_a = LeadRecord(lead_id="l1", label="Hidden Gold", kind=LeadKind.OBJECT, source_id=source_a, certainty=0.8)
    hero.mind.strategic.leads.append(lead_a)
    hero.mind.strategic.source_trust[source_a] = 1.0 # Initial high trust
    
    profile = CognitionCapacityProfile(
        planning_budget=5, judgment_stability=0.7, evidence_quality=0.7, social_bandwidth=3,
        active_slice_limit=8, concern_intake_limit=3, lead_retention_limit=5, candidate_zone_limit=2,
        ally_evaluation_limit=2, blocker_resolution_patience=0.5,
        resume_reliability=0.5, interruption_resistance=0.5,
        abandonment_threshold_mod=0.8, contradiction_sensitivity=1.0, # HIGH SENSITIVITY
        source_trust_learning_rate=1.0, # FAST LEARNING
        detour_depth_limit=2
    )
    
    # 2. Process a failure outcome for this lead
    from src_legacy.ai.states.base import AIContext
    from src_legacy.core.gameplay.faction import FactionRegistry
    faction_reg = FactionRegistry()
    ctx = AIContext(
        actor=hero,
        snapshot=Snapshot.from_world(mock_world),
        config=SimulationConfig(),
        rng=DeterministicRNG(0),
        faction_reg=faction_reg
    )
    
    updates = StrategicLearningService.process_lead_outcome(ctx, lead_a, success=False, profile=profile)
    
    up = next((u for u in updates if isinstance(u, StrategicUpdate)), None)
    assert up is not None
    assert source_a in up.source_trust_updates
    # Trust should have dropped
    assert up.source_trust_updates[source_a] < 1.0
    
    # Apply update to ent
    hero.mind.strategic.source_trust[source_a] = up.source_trust_updates[source_a]
    
    # 3. Add a second lead from the same now-distrusted source
    lead_b = LeadRecord(lead_id="l2", label="Another Lead", kind=LeadKind.OBJECT, source_id=source_a, certainty=0.8)
    hero.mind.strategic.leads.append(lead_b)
    
    # 4. Perform decision pass
    snapshot = Snapshot.from_world(mock_world)
    state, proposal = brain.decide(hero, snapshot)
    
    # Lead B should have a low candidate score or be dropped if trust is low enough
    # but more directly, we can check the StrategicUpdate generated by decisions 
    # if it populates the retained leads.
    
    update = next((u for u in proposal.updates if isinstance(u, StrategicUpdate)), None)
    assert update is not None
    # Verify that the trust drop is persistent in the update (meaning it was applied and reflected)
    # The brain's decided StrategicUpdate will have the final state.
    
def test_severe_failure_abandonment_impact(mock_world, brain):
    """Verify that a project switch/abandonment reflects in strategic drivers."""
    # This is more of a scenario test: 
    # If the current project is 'low priority' and we sense a 'High Danger' concern,
    # we should switch and the driver should explicitly mention it.
    
    hero = Entity(id=1, kind="hero")
    mock_world.add_entity(hero)
    
    # Current low-priority project
    from src_legacy.core.models.strategy import ProjectRecord, ProjectKind
    hero.mind.strategic.projects.append(ProjectRecord(
        project_id="p_junk", kind=ProjectKind.QUEST, label="Junk Quest",
        status=StrategicStatus.ACTIVE, priority=1.0, interruption_threshold=0.1
    ))
    hero.mind.strategic.current_project_id = "p_junk"
    
    # High-priority danger concern
    from src_legacy.core.models.strategy import ConcernRecord, ConcernKind
    hero.mind.strategic.concerns.append(ConcernRecord(
        concern_id="c_death", label="Certain Death", kind=ConcernKind.THREAT,
        priority=5.0, urgency=1.0
    ))
    
    snapshot = Snapshot.from_world(mock_world)
    state, proposal = brain.decide(hero, snapshot)
    
    update = next((u for u in proposal.updates if isinstance(u, StrategicUpdate)), None)
    assert update is not None
    
    # DEBUG
    print(f"\nDRIVERS: {[d.label + ': ' + d.description for d in update.strategic_drivers]}")
    
    assert update.current_project_id != "p_junk"
    
    # Ensure a driver explains the switch
    # Labels to look for: "Project Switch" or "Project Continuity" or "Cognitive Bound Applied"
    assert any(d.label == "Project Switch" for d in update.strategic_drivers)
