"""Tests for the opt-in git hook installer and the pre-commit config (TCK-20261003-PREK-GIT-HOOKS-OPT-IN).

Every test uses a temporary git repository (never this machine's shared .git/hooks) and the real prek binary.
The temporary repository gets a copy of the real hook scripts, config, `codebase/health` and installer, so the
real commit-time path is what runs.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest
import yaml

from codebase.health import registry
from codebase.health.registry import Row

_REPO = Path(__file__).resolve().parent.parent.parent
_BARE = "def f():\n    try:\n        pass\n    except:\n        pass\n"


def _git(cwd: Path, *args: str, env=None, check=True):
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, check=check, env=env)


def _env() -> dict:
    # The hook scripts call `python3` and the shim calls `prek`: the project environment must be first on PATH.
    return {**os.environ, "PATH": f"{Path(sys.executable).parent}{os.pathsep}{os.environ['PATH']}"}


def _row(file, rule, ceiling):
    return Row(file, None, "ruff", rule, ceiling, ceiling, "2026-10-03", False, None)


@pytest.fixture
def repo(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    _git(root, "init", "-q", "-b", "main")
    _git(root, "config", "user.email", "t@example.com")
    _git(root, "config", "user.name", "t")
    shutil.copytree(_REPO / "codebase", root / "codebase", ignore=shutil.ignore_patterns("__pycache__", "baselines"))
    (root / "tools" / "hooks").mkdir(parents=True)
    shutil.copy(_REPO / "tools" / "hooks" / "post-commit-reindex.sh", root / "tools" / "hooks" / "post-commit-reindex.sh")
    shutil.copy(_REPO / ".pre-commit-config.yaml", root / ".pre-commit-config.yaml")
    (root / "pyproject.toml").write_text('[tool.ruff.lint]\nselect = ["E722"]\n')
    (root / "codebase" / "baselines").mkdir(parents=True)
    (root / "src").mkdir()
    (root / "src" / "a.py").write_text(_BARE)
    (root / "src" / "b.py").write_text("x = 1\n")
    registry.write_rows(root / "codebase" / "baselines" / "code_health_exceptions.jsonl", [_row("src/a.py", "E722", 1)])
    _git(root, "add", "-A")
    _git(root, "commit", "-q", "-m", "baseline", "--no-verify")
    return root


def _install(root: Path, action: str = "install"):
    return subprocess.run([sys.executable, str(_REPO / "codebase" / "hooks" / "install_git_hooks.py"), action, "--repo", str(root)],
                          capture_output=True, text=True, env=_env())


def _hook(root: Path, name: str) -> Path:
    return root / ".git" / "hooks" / name


def _snapshot(root: Path) -> dict:
    return {p.name: p.read_bytes() for p in (root / ".git" / "hooks").iterdir() if not p.name.endswith(".sample")}


def test_install_creates_both_hooks_and_warns_that_the_hooks_directory_is_shared(repo):
    done = _install(repo)
    assert done.returncode == 0, done.stderr
    assert "shared by every worktree on this machine" in done.stdout
    assert "post-commit: installed" in done.stdout and "pre-commit: prek hook installed" in done.stdout
    assert os.access(_hook(repo, "post-commit"), os.X_OK) and "File generated by prek" in _hook(repo, "pre-commit").read_text()
    assert _hook(repo, "post-commit").read_bytes() == (repo / "tools" / "hooks" / "post-commit-reindex.sh").read_bytes()


def test_a_second_install_changes_nothing(repo):
    _install(repo)
    before = _snapshot(repo)
    done = _install(repo)
    assert before == _snapshot(repo) and done.returncode == 0
    assert "post-commit: already installed, unchanged" in done.stdout and "pre-commit: prek hook already installed, unchanged" in done.stdout


def test_a_different_existing_post_commit_is_kept_not_overwritten(repo):
    _hook(repo, "post-commit").write_text("#!/bin/sh\necho mine\n")
    done = _install(repo)
    assert _hook(repo, "post-commit").read_text() == "#!/bin/sh\necho mine\n"
    assert "post-commit: a different hook already exists and was kept (not overwritten)" in done.stdout


def test_a_foreign_pre_commit_hook_is_kept_as_legacy_and_still_runs(repo):
    _hook(repo, "pre-commit").write_text("#!/bin/sh\necho foreign-pre-commit-ran\nexit 0\n")
    _hook(repo, "pre-commit").chmod(0o755)
    done = _install(repo)
    assert "pre-commit.legacy" in done.stdout and (repo / ".git" / "hooks" / "pre-commit.legacy").exists()
    (repo / "src" / "b.py").write_text("x = 2\n")
    _git(repo, "add", "src/b.py")
    committed = _git(repo, "commit", "-q", "-m", "change", env=_env(), check=False)
    assert committed.returncode == 0, committed.stderr + committed.stdout
    assert "foreign-pre-commit-ran" in committed.stdout + committed.stderr


def test_post_merge_and_other_hooks_are_never_touched(repo):
    _hook(repo, "post-merge").write_text("#!/bin/sh\necho merge\n")
    _hook(repo, "pre-push").write_text("#!/bin/sh\necho push\n")
    _install(repo)
    assert _hook(repo, "post-merge").read_text() == "#!/bin/sh\necho merge\n"
    assert _hook(repo, "pre-push").read_text() == "#!/bin/sh\necho push\n"
    _install(repo, "uninstall")
    assert _hook(repo, "post-merge").read_text() == "#!/bin/sh\necho merge\n" and _hook(repo, "pre-push").exists()


def test_uninstall_removes_only_what_was_installed_and_restores_the_legacy_hook(repo):
    _hook(repo, "pre-commit").write_text("#!/bin/sh\necho legacy\n")
    _hook(repo, "pre-commit").chmod(0o755)
    _install(repo)
    done = _install(repo, "uninstall")
    assert done.returncode == 0, done.stderr
    assert _hook(repo, "pre-commit").read_text() == "#!/bin/sh\necho legacy\n"
    assert not _hook(repo, "post-commit").exists()


def test_uninstall_leaves_a_post_commit_hook_that_is_not_ours(repo):
    _hook(repo, "post-commit").write_text("#!/bin/sh\necho mine\n")
    _install(repo)
    done = _install(repo, "uninstall")
    assert _hook(repo, "post-commit").read_text() == "#!/bin/sh\necho mine\n"
    assert "post-commit: not ours or not installed, left alone" in done.stdout


def test_the_hooks_directory_is_the_common_one_for_a_worktree(repo, tmp_path):
    _git(repo, "worktree", "add", "-q", str(tmp_path / "wt"), "-b", "side")
    _install(tmp_path / "wt")
    assert "File generated by prek" in _hook(repo, "pre-commit").read_text(), "installed once into the shared directory"


def test_a_real_commit_with_a_new_violation_is_rejected_with_the_ratchet_message(repo):
    _install(repo)
    (repo / "src" / "b.py").write_text(_BARE)
    _git(repo, "add", "src/b.py")
    done = _git(repo, "commit", "-q", "-m", "new violation", env=_env(), check=False)
    assert done.returncode != 0
    text = done.stdout + done.stderr
    assert "NEW violations (no baseline row)" in text and "src/b.py" in text
    assert _git(repo, "log", "--oneline").stdout.count("\n") == 1, "the commit was not created"


def test_a_real_commit_touching_only_grandfathered_code_passes(repo):
    _install(repo)
    (repo / "src" / "a.py").write_text(_BARE + "\nVALUE = 1\n")
    _git(repo, "add", "src/a.py")
    done = _git(repo, "commit", "-q", "-m", "grandfathered only", env=_env(), check=False)
    assert done.returncode == 0, done.stdout + done.stderr


def test_the_hook_checks_the_staged_content_not_the_working_tree(repo):
    """prek stashes unstaged changes: a violation only in the unstaged part must not block the commit."""
    _install(repo)
    (repo / "src" / "b.py").write_text("x = 1\ny = 2\n")
    _git(repo, "add", "src/b.py")
    (repo / "src" / "b.py").write_text("x = 1\ny = 2\n" + _BARE)  # the new violation is unstaged only
    done = _git(repo, "commit", "-q", "-m", "staged part is clean", env=_env(), check=False)
    assert done.returncode == 0, done.stdout + done.stderr
    assert "except:" in (repo / "src" / "b.py").read_text(), "the unstaged change is restored after the hook"


def test_a_worktree_without_the_project_environment_is_not_blocked(repo):
    _install(repo)
    (repo / "src" / "b.py").write_text(_BARE)
    _git(repo, "add", "src/b.py")
    _git(repo, "rm", "-rq", "codebase/health")  # staged deletion: prek restores unstaged changes before the hook runs
    done = _git(repo, "commit", "-q", "-m", "no environment", env=_env(), check=False)
    assert done.returncode == 0, done.stdout + done.stderr
    assert "code-health hook skipped: environment not synced" in done.stdout + done.stderr


# ── the shared hooks directory must never block a worktree that cannot run the hook ─────────────────


def _bare_env() -> dict:
    """A PATH with no prek and no project environment: what a worktree on a plain machine has."""
    env = {**os.environ, "PATH": "/usr/bin:/bin"}
    assert shutil.which("prek", path=env["PATH"]) is None
    return env


def test_a_commit_in_a_checkout_without_the_config_file_is_not_blocked(repo):
    """A branch cut before .pre-commit-config.yaml existed has no config; prek's shim would fail every commit there."""
    _install(repo)
    _git(repo, "rm", "-q", ".pre-commit-config.yaml")
    (repo / "src" / "b.py").write_text(_BARE)  # would be rejected if the hooks ran, but there is no config
    _git(repo, "add", "src/b.py")
    done = _git(repo, "commit", "-q", "-m", "no config in this tree", env=_env(), check=False)
    assert done.returncode == 0, done.stdout + done.stderr


def test_control_a_plain_prek_install_without_the_flag_does_block_a_commit_without_the_config(repo):
    """Proves the test above discriminates: prek's own default install fails here (exit 1)."""
    done = subprocess.run([str(Path(sys.executable).parent / "prek"), "install", "--hook-type", "pre-commit"], cwd=repo, capture_output=True, text=True)
    assert done.returncode == 0, done.stderr
    _git(repo, "rm", "-q", ".pre-commit-config.yaml")
    (repo / "src" / "b.py").write_text("x = 2\n")
    _git(repo, "add", "src/b.py")
    blocked = _git(repo, "commit", "-q", "-m", "x", env=_env(), check=False)
    assert blocked.returncode != 0 and "pre-commit-config.yaml` found in the current directory" in blocked.stdout + blocked.stderr


def _install_with_a_removable_prek(repo: Path, tmp_path: Path) -> Path:
    copy = tmp_path / "bin" / "prek"
    copy.parent.mkdir()
    shutil.copy(Path(sys.executable).parent / "prek", copy)
    done = subprocess.run([sys.executable, str(_REPO / "codebase" / "hooks" / "install_git_hooks.py"), "install", "--repo", str(repo), "--prek", str(copy)],
                          capture_output=True, text=True, env=_env())
    assert done.returncode == 0, done.stderr
    return copy


def test_a_commit_where_prek_cannot_be_resolved_skips_with_a_visible_line_instead_of_failing(repo, tmp_path):
    copy = _install_with_a_removable_prek(repo, tmp_path)
    assert str(copy) in _hook(repo, "pre-commit").read_text(), "the shim hard-codes the prek it was installed with"
    copy.unlink()  # the environment was re-synced without prek, or deleted
    (repo / "src" / "b.py").write_text("x = 2\n")
    _git(repo, "add", "src/b.py")
    done = _git(repo, "commit", "-q", "-m", "prek is gone", env=_bare_env(), check=False)
    assert done.returncode == 0, done.stdout + done.stderr
    assert "pre-commit hook skipped: prek not found (project environment not synced: uv sync)" in done.stdout + done.stderr


def test_control_an_unguarded_shim_with_no_prek_does_fail_every_commit(repo, tmp_path):
    """Proves the test above discriminates: prek's own shim, with prek gone, exits non-zero ('prek: not found')."""
    copy = tmp_path / "bin" / "prek"
    copy.parent.mkdir()
    shutil.copy(Path(sys.executable).parent / "prek", copy)
    subprocess.run([str(copy), "install", "--hook-type", "pre-commit", "--allow-missing-config"], cwd=repo, check=True, capture_output=True)
    copy.unlink()
    (repo / "src" / "b.py").write_text("x = 2\n")
    _git(repo, "add", "src/b.py")
    blocked = _git(repo, "commit", "-q", "-m", "x", env=_bare_env(), check=False)
    assert blocked.returncode != 0


def test_the_guard_is_added_once_and_an_older_unguarded_shim_is_upgraded(repo):
    subprocess.run([str(Path(sys.executable).parent / "prek"), "install", "--hook-type", "pre-commit", "--allow-missing-config"], cwd=repo, check=True, capture_output=True)
    assert "guard added by" not in _hook(repo, "pre-commit").read_text()
    upgraded = _install(repo)
    assert "pre-commit: prek hook already installed, missing-prek guard added" in upgraded.stdout
    once = _hook(repo, "pre-commit").read_bytes()
    again = _install(repo)
    assert _hook(repo, "pre-commit").read_bytes() == once and "unchanged" in again.stdout
    assert once.count(b"guard added by codebase/hooks/install_git_hooks.py") == 1


def test_an_unrecognised_shim_format_is_removed_again_instead_of_left_unguarded(repo, tmp_path):
    """If a future prek writes a shim we cannot guard, install fails and leaves no blocking shim behind."""
    fake = tmp_path / "fake-prek"
    fake.write_text(textwrap.dedent("""\
        #!/bin/sh
        # Stands in for a prek whose generated hook has a format this installer does not know.
        hook="$(git rev-parse --git-path hooks)/pre-commit"
        case "$1" in
          install) printf '#!/bin/sh\\n# File generated by prek: new format\\nrun-something-else\\n' > "$hook"; chmod +x "$hook"; echo "Installed Git hook";;
          uninstall) rm -f "$hook"; echo "Uninstalled";;
        esac
        """))
    fake.chmod(0o755)
    done = subprocess.run([sys.executable, str(_REPO / "codebase" / "hooks" / "install_git_hooks.py"), "install", "--repo", str(repo), "--prek", str(fake)],
                          capture_output=True, text=True, env=_env())
    assert done.returncode == 2 and "unrecognised prek shim" in done.stderr
    assert not _hook(repo, "pre-commit").exists(), "the unguarded shim must not stay behind"


def test_prek_uninstall_still_recognises_and_removes_the_guarded_shim(repo):
    _install(repo)
    assert "guard added by" in _hook(repo, "pre-commit").read_text()
    done = _install(repo, "uninstall")
    assert done.returncode == 0, done.stderr
    assert not _hook(repo, "pre-commit").exists()


def test_a_new_violation_still_blocks_when_the_config_and_prek_are_both_present(repo):
    _install(repo)
    (repo / "src" / "b.py").write_text(_BARE)
    _git(repo, "add", "src/b.py")
    done = _git(repo, "commit", "-q", "-m", "violation", env=_env(), check=False)
    assert done.returncode != 0 and "NEW violations (no baseline row)" in done.stdout + done.stderr


# ── static: the config and the opt-in rule ────────────────────────────────────


def test_the_config_lists_exactly_the_two_local_system_hooks():
    config = yaml.safe_load((_REPO / ".pre-commit-config.yaml").read_text())
    assert config["minimum_prek_version"] == "0.5.4"
    (local,) = config["repos"]
    assert local["repo"] == "local"
    hooks = {h["id"]: h for h in local["hooks"]}
    assert set(hooks) == {"code-health-ratchet", "uv-lock-check"}
    assert all(h["language"] == "system" for h in hooks.values()), "no environment build, no network"
    assert hooks["code-health-ratchet"]["files"] == r"^src/.*\.py$"
    assert all(h["verbose"] is True for h in hooks.values()), "a skip line from a passing hook must stay visible"
    assert hooks["uv-lock-check"]["files"] == r"^(pyproject\.toml|uv\.lock)$" and hooks["uv-lock-check"]["pass_filenames"] is False
    assert "uv lock --check --offline" in (_REPO / "codebase" / "hooks" / "uv_lock_pre_commit.sh").read_text(), "a commit never waits for the network"


def test_the_makefile_targets_only_call_the_installer_and_name_the_risk():
    text = (_REPO / "Makefile").read_text()
    install = next(l for l in text.splitlines() if l.startswith("install-prek-hooks:"))
    assert "OPT-IN" in install and "EVERY worktree" in install
    assert "python3 -m codebase.hooks.install_git_hooks install" in text and "python3 -m codebase.hooks.install_git_hooks uninstall" in text
    assert "OVERWRITES" in next(l for l in text.splitlines() if l.startswith("install-hooks:"))


def test_nothing_installs_hooks_implicitly():
    """No other Makefile target, script, workflow or Claude Code configuration may install or depend on the hooks."""
    lines = (_REPO / "Makefile").read_text().splitlines()
    for line in lines:
        if line.startswith(("install-prek-hooks:", "uninstall-prek-hooks:", "install-hooks:", ".PHONY")) or line.startswith("\t") or ":" not in line:
            continue
        dependencies = line.split(":", 1)[1].split("##")[0]
        assert "install-prek-hooks" not in dependencies and "install-hooks" not in dependencies, line
    for name in ("install:", "install-py:"):
        assert "hooks" not in next(l for l in lines if l.startswith(name)).split("##")[0]
    needles = ("install-prek-hooks", "install_git_hooks", "prek install")
    scanned = [p for pattern in (".github/workflows/*.yml", "tools/**/*.sh", "tools/**/*.py", "make.bat", ".claude/settings*.json")
               for p in _REPO.glob(pattern)]
    def code(path: Path) -> str:  # comments may name the opt-in target; only executable lines count
        return "\n".join(l for l in path.read_text(errors="replace").splitlines() if not l.lstrip().startswith("#"))

    offenders = [p.relative_to(_REPO).as_posix() for p in scanned
                 if p.name != "install_git_hooks.py" and any(n in code(p) for n in needles)]
    assert offenders == [], offenders
    recipe_lines = [l for l in lines if l.startswith("\t") and any(n in l for n in needles)]
    assert recipe_lines == ["\tpython3 -m codebase.hooks.install_git_hooks install", "\tpython3 -m codebase.hooks.install_git_hooks uninstall"]
