"""The terrain palette `terrain-v1` and the GPL exports of both committed palettes (`TCK-20261010-VISUAL-ASSETS-PALETTE-AS-DATA`).

`visual_assets/palettes/terrain-v1.json` is exactly `build_terrain_palette()`: the Live Map terrain fills read, read-only, from `frontend/src/constants/colors.ts` (the same reader `icons-v1` uses), one per
`terrain-v1` key, in key order. `*.gpl` are GIMP palettes (loadable by Aseprite: Palette > Load) generated from the JSON files and drift-guarded by tests, so the files drawing, lint and the editor see are one
source. Pure Python; `python -m visual_assets.review.palette_data` prints a summary, `--write` rewrites the committed files.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from visual_assets.review.icon_palette import PALETTE_FILE as ICONS_FILE
from visual_assets.review.icon_palette import SET_ID, terrain_fills

PALETTES = ICONS_FILE.parent
TERRAIN_FILE = PALETTES / "terrain-v1.json"
PALETTE_FILES = {"icons-v1": ICONS_FILE, "terrain-v1": TERRAIN_FILE}


def build_terrain_palette() -> dict:
    entries: list[dict] = []
    seen: dict[str, int] = {}
    for key, colour in terrain_fills().items():
        if colour in seen:
            entries[seen[colour]]["also"] = entries[seen[colour]].get("also", []) + [f"terrain: {key}"]
            continue
        seen[colour] = len(entries)
        entries.append({"color": colour, "role": "terrain", "source": key})
    return {
        "record_type": "terrain_palette", "palette_id": "terrain-v1",
        "decision": "derived read-only from the Live Map terrain fills in frontend/src/constants/colors.ts, one per terrain-v1 key; editing the fills is the frontend's, not this file's",
        "derivation": "visual_assets/review/palette_data.py::build_terrain_palette (the file is exactly its output)", "terrain_set": SET_ID,
        "colors": [e["color"] for e in entries], "entries": entries,
    }


def json_text(palette: dict) -> str:
    return json.dumps(palette, indent=1) + "\n"


def gpl_text(palette: dict) -> str:
    """A GIMP palette: one line per entry, `R G B  <hex> <role>: <source>`; deterministic."""
    lines = ["GIMP Palette", f"Name: {palette['palette_id']}", "Columns: 8", "#"]
    for entry in palette["entries"]:
        colour = entry["color"]
        r, g, b = int(colour[1:3], 16), int(colour[3:5], 16), int(colour[5:7], 16)
        lines.append(f"{r:3d} {g:3d} {b:3d}\t{colour[1:]} {entry['role']}: {entry['source']}")
    return "\n".join(lines) + "\n"


def committed_gpl(palette_id: str) -> Path:
    return PALETTES / f"{palette_id}.gpl"


def expected_files() -> dict[Path, str]:
    """Every generated file and its exact text (icons-v1.json is generated by `icon_palette`, so its content is read, not rebuilt, here)."""
    icons = json.loads(ICONS_FILE.read_text(encoding="utf-8"))
    terrain = build_terrain_palette()
    return {TERRAIN_FILE: json_text(terrain), committed_gpl("icons-v1"): gpl_text(icons), committed_gpl("terrain-v1"): gpl_text(terrain)}


if __name__ == "__main__":
    files = expected_files()
    if "--write" in sys.argv:
        for path, text in files.items():
            path.write_text(text, encoding="utf-8")
    for path, text in files.items():
        print(f"{path.relative_to(PALETTES.parent.parent)}  {len(text.splitlines())} lines  {'written' if '--write' in sys.argv else 'would write'}")
